# Generated by Django 5.2.7 on 2025-11-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured",
            field=models.BooleanField(null=True, verbose_name="featured"),
        ),
    ]
